# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='moder_cat',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Category'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='moder_tags',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Персонал'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='moderated',
            field=models.BooleanField(default=False, verbose_name='Модерируется'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='2017/2/12/'),
        ),
    ]
