# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
