# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170212_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='moder_tags',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Tag', verbose_name='Модерирует тэги'),
        ),
    ]
