# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161211_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='ratingpost',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='ratingtag',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='ratinguser',
            name='votes',
        ),
        migrations.AddField(
            model_name='ratingcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Comment'),
        ),
    ]
