# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160911_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
    ]
