# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 20:40
from __future__ import unicode_literals

import blog.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170212_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=blog.models.myUser.user_directory_path, verbose_name='Аватар'),
        ),
    ]
