# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161211_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='2016/12/12/'),
        ),
    ]
