# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 20:12
from __future__ import unicode_literals

import blog.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170414_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_thumb_ext',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='2017/4/20/', validators=[blog.functions.validate_post_image]),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image_gif',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='2017/4/20/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='2017/4/20/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=3000),
        ),
    ]
