# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170212_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='moderator',
            field=models.BooleanField(default=False, verbose_name='Модератор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='2017/2/16/'),
        ),
    ]
