# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:05
from __future__ import unicode_literals

import blog.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170420_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='2017/4/24/', validators=[blog.functions.validate_post_image]),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image_gif',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='2017/4/24/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='2017/4/24/'),
        ),
    ]
