# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170216_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='can_comment',
            field=models.BooleanField(default=True, verbose_name='Может комментировать'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='can_post',
            field=models.BooleanField(default=True, verbose_name='Может добавлять посты'),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.BooleanField(default=True, verbose_name='Разрешено комментировать'),
        ),
        migrations.AddField(
            model_name='post',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Не разрешать редактировать автору'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='2017/2/17/'),
        ),
    ]
