# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20161212_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Comments'},
        ),
    ]
