# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20161118_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='url',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
