# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 16:09
from __future__ import unicode_literals

import blog.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170424_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='2017/4/29/', validators=[blog.functions.validate_post_image]),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image_gif',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='2017/4/29/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='2017/4/29/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
