# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170217_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='post',
            name='rateable',
            field=models.BooleanField(default=True, verbose_name='Разрешено голосовать'),
        ),
    ]
