# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160910_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_it_staff',
            field=models.BooleanField(default=False, verbose_name='Is stuff'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_it_superuser',
            field=models.BooleanField(default=False, verbose_name='Is admin'),
        ),
    ]
