# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20161120_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
