# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_myuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='private',
            field=models.BooleanField(default=False, verbose_name='NSFW'),
        ),
    ]
