# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160928_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='2016/10/2/'),
        ),
    ]
