# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20161120_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rate_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
