# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20161120_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='rate_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
