# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_post_post_image_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='2017/2/24/'),
        ),
    ]
