# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20161002_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='moderated',
            field=models.BooleanField(default=True, verbose_name='Moderated'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='2016/10/6/'),
        ),
    ]
