# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170224_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votepost',
            name='post',
        ),
        migrations.DeleteModel(
            name='VotePost',
        ),
    ]
