# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20161215_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservotes',
            name='votes',
            field=models.IntegerField(default=10),
        ),
    ]
