# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170224_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='2017/2/26/'),
        ),
    ]
