# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_uservotes_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_thumbnail',
            field=models.ImageField(blank=True, upload_to='2016/12/17/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='2016/12/17/'),
        ),
    ]
