# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20161120_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservotes',
            name='userid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratingpost',
            name='rating_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='ratingtag',
            name='rating_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='ratinguser',
            name='rating_id',
            field=models.IntegerField(unique=True),
        ),
    ]
