# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20161006_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', related_query_name='tags', to='blog.Tag'),
        ),
    ]
