# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20161120_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingpost',
            old_name='rating_id',
            new_name='ratingid',
        ),
        migrations.RenameField(
            model_name='ratingtag',
            old_name='rating_id',
            new_name='ratingid',
        ),
        migrations.RenameField(
            model_name='ratinguser',
            old_name='rating_id',
            new_name='ratingid',
        ),
    ]
