# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20161217_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='votes_count',
            field=models.CharField(choices=[('U', 'Unlimited'), ('N', 'Normal'), ('B', 'Blocked')], default='N', max_length=1),
        ),
    ]
