# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_myuser_votes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='has_votes',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='2016/12/18/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_thumbnail',
            field=models.ImageField(blank=True, upload_to='2016/12/18/'),
        ),
    ]
