# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170227_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Рейтинг'),
        ),
    ]
