# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20161120_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingpost',
            name='ratingid',
        ),
        migrations.RemoveField(
            model_name='ratingtag',
            name='ratingid',
        ),
        migrations.RemoveField(
            model_name='ratinguser',
            name='ratingid',
        ),
        migrations.RemoveField(
            model_name='uservotes',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='votepost',
            name='vote_id',
        ),
    ]
