# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20161120_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='2016/11/22/'),
        ),
        migrations.AlterField(
            model_name='ratingpost',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ratingtag',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ratinguser',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='uservotes',
            name='votes',
            field=models.IntegerField(default=10),
        ),
    ]
