# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20161224_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingcomment',
            old_name='user',
            new_name='comment',
        ),
    ]
