# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20161123_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='main_tag',
        ),
        migrations.AddField(
            model_name='post',
            name='main_tag1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Tag'),
        ),
    ]
