# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20170227_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='ratingpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='ratingtag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='ratinguser',
            name='user',
        ),
        migrations.DeleteModel(
            name='RatingComment',
        ),
        migrations.DeleteModel(
            name='RatingPost',
        ),
        migrations.DeleteModel(
            name='RatingTag',
        ),
        migrations.DeleteModel(
            name='RatingUser',
        ),
    ]
