# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20161123_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='has_votes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='2016/11/24/'),
        ),
    ]
