# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20170106_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=700),
        ),
    ]
