# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20170309_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='2017/3/10/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='2017/3/10/'),
        ),
    ]
