# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20161018_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='url',
            field=models.CharField(blank=True, max_length=33, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='2016/10/19/'),
        ),
    ]
