# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20161124_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingpost',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ratingtag',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ratinguser',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
