# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20161124_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='votepost',
            name='counted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='2016/11/26/'),
        ),
    ]
