# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 14:06
from __future__ import unicode_literals

import blog.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20170310_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='2017/3/11/', validators=[blog.functions.validate_post_image]),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='2017/3/11/'),
        ),
    ]
