# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20161019_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='url',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
    ]
