# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20170108_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_image_srcset',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
