# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 16:40
from __future__ import unicode_literals

import blog.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20170311_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='moder_cat',
            new_name='moderator_of_categories',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='moder_tags',
            new_name='moderator_of_tags',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='votes_count',
            new_name='votes_amount',
        ),
        migrations.RenameField(
            model_name='uservotes',
            old_name='count',
            new_name='vote_type',
        ),
        migrations.RenameField(
            model_name='uservotes',
            old_name='votes',
            new_name='votes_amount',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=700, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='2017/3/15/', validators=[blog.functions.validate_post_image]),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='2017/3/15/'),
        ),
    ]
