# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20161019_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='url',
        ),
    ]
