# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_remove_tag_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='url',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
