# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_tag_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='maintag',
            field=models.CharField(blank=True, max_length=33),
        ),
    ]
