# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20170108_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_thumbnail',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='2017/1/22/'),
        ),
    ]
