# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20161127_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='src1366',
            field=models.ImageField(blank=True, upload_to='2016/11/29/'),
        ),
        migrations.AddField(
            model_name='post',
            name='src1600',
            field=models.ImageField(blank=True, upload_to='2016/11/29/'),
        ),
        migrations.AddField(
            model_name='post',
            name='src1920',
            field=models.ImageField(blank=True, upload_to='2016/11/29/'),
        ),
        migrations.AddField(
            model_name='post',
            name='src480',
            field=models.ImageField(blank=True, upload_to='2016/11/29/'),
        ),
        migrations.AddField(
            model_name='post',
            name='src800',
            field=models.ImageField(blank=True, upload_to='2016/11/29/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='2016/11/29/'),
        ),
    ]
