# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_post_maintag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='maintag',
            new_name='main_tag',
        ),
    ]
