# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20161129_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='src1366',
        ),
        migrations.RemoveField(
            model_name='post',
            name='src1600',
        ),
        migrations.RemoveField(
            model_name='post',
            name='src1920',
        ),
        migrations.RemoveField(
            model_name='post',
            name='src480',
        ),
        migrations.RemoveField(
            model_name='post',
            name='src800',
        ),
    ]
