# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20170122_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='2017/1/23/'),
        ),
    ]
