# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 13:47
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20161019_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=blog.models.myUser.user_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='2016/10/22/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='url',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
