# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 10:31
from __future__ import unicode_literals

import blog.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20161022_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(upload_to=blog.models.myUser.user_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='2016/10/23/'),
        ),
    ]
