# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 18:21
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20161205_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image_srcset',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.Tag.tags_directory_path),
        ),
    ]
