# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20161205_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='has_srcset',
            field=models.BooleanField(default=False),
        ),
    ]
