# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_tag_has_srcset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='has_srcset',
        ),
    ]
