# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_tag_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'get_latest_by': 'created', 'verbose_name_plural': 'tags'},
        ),
    ]
