# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 20:30
from __future__ import unicode_literals

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20161205_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=froala_editor.fields.FroalaField(blank=True, max_length=700, null=True),
        ),
    ]
